services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    mem_limit: 512m
    container_name: shipbuilder-go
    command: air ./cmd/main.go -b 0.0.0.0
  web-debug:
    build:
      context: . 
      dockerfile: Dockerfile.debug
    env_file:
      - .env
    ports:
      - "4000:4000"
      - "3001:3000"
    mem_limit: 512m
    container_name: shipbuilder-go-debugger
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    mem_limit: 512m
    container_name: shipbuilder_db

volumes:
  postgres-db:
